# Interactive Research Tool for Optical flow and Perception Research
# /run/media/medathati/4TBInt/MedathatiExt/Work/OpticalFlow/Code/InteractiveResearchTool/data_parser.py
#
# Naga Venkata Kartheek Medathati
# April 27th 2020
# mnvhere@gmail.com

# Notes: 
# In case of gratings and plaids: 
#   - speed is the velocity of the grating in it's normal
#   - velocity is the 2D (vx,vy) vx: along horizontal, vy: along vertical
#   - Optical flow axis: 
#        vx-> 3 o' clock/towards right positive,   
#        vy-> 6 o' clock/towards the bottom of the image positive


Dataset: Wallach
base_dir: &base /run/media/medathati/4TBInt/MedathatiExt/Work/OpticalFlow/
docker: dockerImage
launcher: script_to_launch

stimuli_types: [&circles 'circles',
                &rectangles 'rectangles',
                &lines 'lines',
                &gratings 'gratings',
                &plaids 'plaids',
                &hybridplaids 'hybridplaids',
                &barberpoles 'barberpoles',
                &barberplaids 'barberplaids',
                &transparent_dots 'transparent_dots',
                &transparent_gratings 'transparent_gratings']

*circles:
  'params': 
    'contrast': [255]
    'radii': [120]
    'isfilled': ['True','False']
    'velocities': [(1.0,.2)]

*rectangles:
  'params':
    'contrast': [255]
    'lengths': [10]
    'orientations': [90]
    'aspect_ratios': [0.25,1,1.25]
    'velocities':

*lines:
  'params':
    'contrast': 
    'length':
    'orientation':
    'aperture':

*gratings:
  'params':
    'contrast':
    'frequency':
    'aperture':
    'orientation':
    'speed':
    'velocities':

*plaids:
  'params':
    'contrast':
    'frequency1':
    'frequency2':
    'speed1':
    'speed2':
    'aperture':

*hybridplaids:
  'params':
    'contrast':
    'frequencies':
    'aperture':

*barberpoles:
  'params':
    'rect_lengths': [200, 300]
    'rect_widths': [40, 60]
    'frequencies': [0.1, 0.05, 0.033]
    'grating_orientations':
    'aperture_orientations': [0, 45, 90, 135]

*barberplaids:
  'params':
    'rect_lengths': [200, 300]
    'rect_widths': [40, 60]
    'frequencies': [0.1, 0.05, 0.033]
    'orientations':
    'orientation_offset':
    'aperture_orientations': [0, 45, 90, 135]

*transparent_dots:
  'params':
    'num_dots': [200, 400]
    'dot_radii': [2, 4]
    'speed_pairs':
    'direction_pairs':

*transparent_gratings:
  'params':
    'frequencies': [0.1, 0.05, 0.033]
    'aperture_radius': 100
    'orientations':
    'orientation_offset':






