# Interactive Research Tool for Optical flow and Perception Research
# /run/media/medathati/4TBInt/MedathatiExt/Work/OpticalFlow/Code/InteractiveResearchTool/data_parser.py
#
# Naga Venkata Kartheek Medathati
# April 27th 2020
# mnvhere@gmail.com

# Notes: 
# In case of gratings and plaids: 
#   - speed is the velocity of the grating in it's normal
#   - velocity is the 2D (vx,vy) vx: along horizontal, vy: along vertical
#   - Optical flow axis: 
#        vx-> 3 o' clock/towards right positive,   
#        vy-> 6 o' clock/towards the bottom of the image positive


Dataset: Wallach
base_dir: &base /run/media/medathati/4TBInt/MedathatiExt/Work/OpticalFlow/
docker: dockerImage
launcher: script_to_launch

stimuli_types: [&circles 'circles',
                &rectangles 'rectangles',
                &lines 'lines',
                &gratings 'gratings',
                &plaids 'plaids',
                &hybridplaids 'hybridplaids']

*circles:
  'params': 
    'contrast': [255]
    'radii': [120]
    'isfilled': ['True','False']
    'velocities': [(1.0,.2)]

*rectangles:
  'params':
    'contrast': [255]
    'lengths': [10]
    'orientations': [90]
    'aspect_ratios': [0.25,1,1.25]
    'velocities':

*lines:
  'params':
    'contrast': 
    'length':
    'orientation':
    'aperture':

*gratings:
  'params':
    'contrast':
    'frequency':
    'aperture':
    'orientation':
    'speed':
    'velocities':

*plaids:
  'params':
    'contrast':
    'frequency1':
    'frequency2':
    'speed1':
    'speed2':
    'aperture':

*hybridplaids:
  'params':
    'contrast':
    'frequencies':
    'aperture':










